TOPDIR ?= ../..
include $(TOPDIR)/.config

$(C_BEAM_SUPPORT)_SRC += protocols/c-beam/c-beam.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
