TOPDIR ?= ../..
include $(TOPDIR)/.config

$(NRF24L01_PROTOCOL_R0KET_SUPPORT)_SRC += hardware/nrf24l01/r0ket.c
##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
